name: Deploy CoinFlipper CAPTCHA

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:3.35.7
    env:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Flutter pub get
        working-directory: captcha/coinflipper
        run: flutter pub get

      # (Optional) code generation step placeholder - uncomment if needed
      # - name: Generate code
      #   working-directory: captcha/coinflipper
      #   run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Build web (release)
        working-directory: captcha/coinflipper
        # Deploy Flutter build at project site root: https://jesseriemens.github.io/coinflipper/
        run: flutter build web --release --base-href /coinflipper/ --no-web-resources-cdn --no-wasm-dry-run

      - name: Prepare site directory
        run: |
          mkdir -p _site
          # Root landing page (optional separate from Flutter app index)
          cp index.html _site/index.html
          # Captcha HTML at /coinflipper/captcha.html
          if [ -f captcha/captcha.html ]; then cp captcha/captcha.html _site/captcha.html; fi
          # Place Flutter build at site root so its own index.html is accessible directly
          cp -R captcha/coinflipper/build/web/* _site/

      - name: Fix permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
